import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Script from "next/script";
import HeaderWeb from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  params,
  children,
}: {
  params: { site_id: string };
  children: React.ReactNode;
}) {
  return (
    <>
      {/* <Header/> */}
      <html lang="en">
        <head>
          <Script src="http://localhost:3000"></Script>
        </head>
        <body className={inter.className}>
          <HeaderWeb />
          {children}
        </body>
      </html>
    </>
  );
}
