"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Script from "next/script";
import HeaderWeb from "@/components/Header";
import { useCartStore } from "@/stores/cartStore";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",

// };

export default function Layout({
  params,
  children,
}: {
  params: { site_id: string };
  children: React.ReactNode;
}) {
  // initialise cart session
  const initializeSession = useCartStore((state) => state.initializeSession);

  useEffect(() => {
    const init = async () => {
      try {
        await initializeSession();
        // Force rehydration after initialization
        useCartStore.persist.rehydrate();
      } catch (error) {
        console.error('Session initialization failed:', error);
      }
    };
    init();
  }, [initializeSession]);

  return (
    <>
      {/* <Header/> */}
      <html lang="en">
        <head>
          <Script src="http://localhost:3000"></Script>
        </head>
        <body className={inter.className}>
          <HeaderWeb />
          <div className="mx-0">{children}</div>
        </body>
      </html>
    </>
  );
}
